config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
  post "test_file_upload", to: "application#file_upload", as: "test_file_upload"
  get "test_file_upload", to: "application#file_upload_form", as: :file_upload_form

end

app/models/one_c_log.rb
class OneCLog < ActiveRecord::Base
  has_attached_file :attachment
  attr_accessible :attachment
  do_not_validate_attachment_file_type :attachment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception

  before_action do
    @pure_html_form = true
  end

  def file_upload
    h = {}
    h[:attachment] = params[:filename]
    puts "params: #{h.inspect}"
    params[:one_c_log][:attachment] = params["filename"]
    @log = OneCLog.create(h)

    if @pure_html_form
      render "pure_html_form"
    else
      render "file_upload_form"
    end

  end

  def file_upload_form
    @log = OneCLog.new

    if @pure_html_form
      render "pure_html_form"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/file_upload_form.html.slim
= simple_form_for @log, url: test_file_upload_path do |f|
  div
    |attachment exists: #{@log.attachment.exists?.inspect}

  = f.input :attachment, as: :file, input_html: { name: "filename" }
  = f.button :submit

app/views/application/pure_html_form.html.slim
form action=test_file_upload_path method="post" accept-charset="UTF-8"
  /enctype="multipart/form-data"
  input type="file" name="filename"
  button type="submit"
    |Create

app/views/application/simple_form_html_form.html.slim
form#new_one_c_log.simple_form.new_one_c_log accept-charset="UTF-8" action="/test_file_upload" enctype="multipart/form-data" method="post" novalidate="novalidate"
  /input name="utf8" type="hidden" value="✓"
  /input name="authenticity_token" type="hidden" value="EU/9K9HwBgpqvPV74AkKcigPlKkKZy/ihoDl6jQ5+z4K59aTKsS9JRA7eJlg1KSfsPEgi5AoELT8Q8Obnt8Qhw=="
  div
    | attachment exists: false
  .input.file.optional.one_c_log_attachment
    input#one_c_log_attachment.file.optional name="filename" type="file"
  input.btn name="commit" type="submit" value=("Create One c log")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FileUpload</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.slim
a href=file_upload_form_path
  |File upload form